/* Surgical Logbook v10: Supabase cloud + IndexedDB offline cache. */
const cfg=window.SUPABASE_CONFIG||{};
const sb=cfg.url&&cfg.publishableKey?window.supabase.createClient(cfg.url,cfg.publishableKey):null;
const $=id=>document.getElementById(id); const DB='surgical-logbook-v10'; const STORE='cases'; const DRAFT='drafts'; const FILES='files';
const CATEGORIES=['GI','HPB','Colorectal','Breast','Endocrine','Hernia','Trauma','Surgical Oncology','Vascular','Thoracic','Urology','Proctology','Other'];
const PROCEDURES=['Exploratory laparotomy','Appendicectomy','Open cholecystectomy','Laparoscopic cholecystectomy','Hernia repair','TEP','TAPP','Colectomy','Hemicolectomy','Anterior resection','APR','Ileostomy','Colostomy','Thyroidectomy','Mastectomy','Breast conserving surgery','Axillary dissection','Modified radical mastectomy','Whipple procedure','Hepatectomy','Gastrectomy','Splenectomy','Pancreatic surgery','Trauma laparotomy','Laparotomy with bowel resection','Stoma reversal','Proctectomy','Haemorrhoidectomy','Fistulectomy','LIFT','Other'];
let currentUser=null,cases=[],editing=null,realtime=null,syncing=false,dirtyDraftTimer=null;
const fields=['caseNumber','patientName','age','sex','crUhid','wardUnit','admissionDate','surgeryDate','dischargeDate','caseType','myRole','approach','preopDiagnosis','postopDiagnosis','procedureName','procedureCategory','primarySurgeon','consultant','anaesthesia','assistants','findings','operativeSteps','complications','complexity','supervision','outcome','incisionTime','closureTime','duration','bloodLoss','drainPlaced','drainType','specimen','hpeNumber','hpeDiagnosis','hpeStatus','hpeSentDate','hpeReceivedDate','followupDate','followupOutcome','remarks'];
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function notify(msg){$('authMsg').textContent=msg||''}
function formMsg(msg){$('formMsg').textContent=msg||''}
function val(id){return $(id)?.value?.trim()||''}
function setv(id,v){if($(id))$(id).value=v??''}
function isoNow(){return new Date().toISOString()}
function uid(){return crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)})}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,2);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'id'});if(!d.objectStoreNames.contains(DRAFT))d.createObjectStore(DRAFT,{keyPath:'id'});if(!d.objectStoreNames.contains(FILES))d.createObjectStore(FILES,{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function idbPut(store,obj){const d=await openDB();return new Promise((res,rej)=>{const tx=d.transaction(store,'readwrite');tx.objectStore(store).put(obj);tx.oncomplete=()=>res(obj);tx.onerror=()=>rej(tx.error)})}
async function idbGetAll(store){const d=await openDB();return new Promise((res,rej)=>{const r=d.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function idbGet(store,id){const d=await openDB();return new Promise((res,rej)=>{const r=d.transaction(store).objectStore(store).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function idbDelete(store,id){const d=await openDB();return new Promise((res,rej)=>{const tx=d.transaction(store,'readwrite');tx.objectStore(store).delete(id);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
function setSync(status){const b=$('syncBadge');b.className='badge';if(status==='synced'){b.textContent='✓ Synced';b.classList.add('online')}else if(status==='syncing'){b.textContent='⟳ Syncing';b.classList.add('pending')}else if(status==='pending'){b.textContent='⚠ Pending sync';b.classList.add('pending')}else if(status==='failed'){b.textContent='✕ Sync failed';b.classList.add('error')}else b.textContent='Offline'}
function visibleCases(){return cases.filter(c=>!c.is_deleted)}
function stats(casesIn=visibleCases()){const n=casesIn.length;return {total:n,primary:casesIn.filter(c=>c.my_role==='Primary Surgeon').length,first:casesIn.filter(c=>c.my_role==='First Assistant').length,second:casesIn.filter(c=>c.my_role==='Second Assistant').length,observer:casesIn.filter(c=>c.my_role==='Observer').length,emergency:casesIn.filter(c=>c.case_type==='Emergency').length,elective:casesIn.filter(c=>c.case_type==='Elective').length,month:casesIn.filter(c=>String(c.surgery_date||'').startsWith(new Date().toISOString().slice(0,7))).length,year:casesIn.filter(c=>String(c.surgery_date||'').startsWith(new Date().getFullYear())).length,pendingHpe:casesIn.filter(c=>c.hpe_status==='pending').length,pendingSync:casesIn.filter(c=>c.sync_status&&c.sync_status!=='synced').length,complications:casesIn.filter(c=>c.complications&&c.complications.trim()).length,reexploration:casesIn.filter(c=>(c.conversion_reexploration||'').trim()||c.outcome==='Re-exploration').length}}
function renderStats(){const s=stats();$('stats').innerHTML=[['Total cases',s.total],['Primary',s.primary],['First assistant',s.first],['Second assistant',s.second],['Observer',s.observer],['Emergency',s.emergency],['Elective',s.elective],['HPE pending',s.pendingHpe]].map(x=>`<div class="stat"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('');$('backupSyncStatus').textContent=s.pendingSync?`${s.pendingSync} pending`:'✓ Synced'}
function card(c){const st=c.sync_status==='synced'?'synced':c.sync_status==='failed'?'failed':'pending';return `<article class="case-card" data-id="${esc(c.id)}"><div><h3>${esc(c.procedure_name||'Untitled procedure')}</h3><div class="case-meta"><b>${esc(c.case_number||'Pending ID')}</b> · ${esc(c.surgery_date||'No date')} · ${esc(c.case_type||'')}<br>${esc(c.my_role||'')} · ${esc(c.approach||'')}<br>${esc(c.preop_diagnosis||c.postop_diagnosis||'No diagnosis')}</div><span class="status ${st}">${st==='synced'?'✓ Synced':st==='failed'?'✕ Sync failed':'⚠ Pending sync'}</span></div><button class="secondary openBtn">View</button></article>`}
function renderRecent(){const arr=visibleCases().sort((a,b)=>(b.surgery_date||'').localeCompare(a.surgery_date||'')).slice(0,6);$('recentList').innerHTML=arr.length?arr.map(card).join(''):'<div class="empty">No cases yet. Add your first case.</div>'}
function fillLists(){document.querySelector('#procedureList').innerHTML=PROCEDURES.map(x=>`<option value="${esc(x)}">`).join('');document.querySelector('#categoryList').innerHTML=CATEGORIES.map(x=>`<option value="${esc(x)}">`).join('');const years=[...new Set(visibleCases().map(c=>(c.surgery_date||'').slice(0,4)).filter(Boolean))].sort().reverse();$('yearFilter').innerHTML='<option value="">All years</option>'+years.map(y=>`<option>${y}</option>`).join('');$('statYear').innerHTML='<option value="">All years</option>'+years.map(y=>`<option>${y}</option>`).join('');}
function filtered(){const q=val('search').toLowerCase(),r=val('roleFilter'),t=val('typeFilter'),a=val('approachFilter'),y=val('yearFilter'),cat=val('categoryFilter'),h=val('hpeFilter');return visibleCases().filter(c=>{const blob=JSON.stringify(c).toLowerCase();return(!q||blob.includes(q))&&(!r||c.my_role===r)&&(!t||c.case_type===t)&&(!a||c.approach===a)&&(!y||String(c.surgery_date||'').startsWith(y))&&(!cat||c.procedure_category===cat)&&(!h||c.hpe_status===h)}).sort((x,y)=>(y.surgery_date||'').localeCompare(x.surgery_date||''))}
function renderCases(){const arr=filtered();$('caseList').innerHTML=arr.length?arr.map(card).join(''):'<div class="empty">No matching cases.</div>'}
function renderAll(){renderStats();fillLists();renderRecent();renderCases();renderAnalytics();}
function renderAnalytics(){const y=val('statYear'),arr=visibleCases().filter(c=>!y||String(c.surgery_date||'').startsWith(y));const counts=(key)=>{const m={};arr.forEach(c=>{const k=c[key]||'Not specified';m[k]=(m[k]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1])};const draw=(items)=>{const max=items[0]?.[1]||1;return items.slice(0,15).map(([k,n])=>`<div class="bar-row"><span>${esc(k)}</span><div class="bar"><i style="width:${Math.max(3,n/max*100)}%"></i></div><b>${n}</b></div>`).join('')||'<span class="muted">No data</span>'};$('procedureStats').innerHTML=draw(counts('procedure_name'));$('categoryStats').innerHTML=draw(counts('procedure_category'));$('consultantStats').innerHTML=draw(counts('consultant_supervisor'));$('statCards').innerHTML=(()=>{const s=stats(arr);return [['Total',s.total],['Primary',s.primary],['First Assistant',s.first],['Second Assistant',s.second],['Observer',s.observer],['Emergency',s.emergency],['Elective',s.elective],['Open',arr.filter(c=>c.approach==='Open').length],['Laparoscopic',arr.filter(c=>c.approach==='Laparoscopic').length],['Complications',s.complications],['Re-explorations',s.reexploration],['HPE pending',s.pendingHpe]].map(x=>`<div class="stat"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')})()}
function showPage(name){document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));const id=name==='home'?'homePage':name==='cases'?'casesPage':name==='stats'?'statsPage':'backupPage';$(id).classList.remove('hidden');$('pageTitle').textContent=name==='home'?'Home':name[0].toUpperCase()+name.slice(1);document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));renderAll()}
function showMain(){ $('authView').classList.add('hidden');$('mainView').classList.remove('hidden');$('bottomNav').classList.remove('hidden');$('logoutBtn').classList.remove('hidden');$('settingsBtn').classList.remove('hidden');$('syncBtn').classList.remove('hidden');showPage('home') }
function showAuth(){ $('authView').classList.remove('hidden');$('mainView').classList.add('hidden');$('bottomNav').classList.add('hidden');$('logoutBtn').classList.add('hidden');$('settingsBtn').classList.add('hidden');$('syncBtn').classList.add('hidden') }
function calcDuration(){const a=val('incisionTime'),b=val('closureTime');if(!a||!b){setv('duration','');return}let x=a.split(':').map(Number),y=b.split(':').map(Number);let m=(y[0]*60+y[1])-(x[0]*60+x[1]);if(m<0)m+=1440;setv('duration',`${Math.floor(m/60)} h ${m%60} min`)}
async function nextCaseNumber(){if(!navigator.onLine||!sb||!currentUser){const y=new Date().getFullYear();const nums=visibleCases().map(c=>c.case_number).filter(x=>x&&x.startsWith(y+'-')).map(x=>parseInt(x.slice(5),10)).filter(Number.isFinite);return `${y}-${String((Math.max(0,...nums)+1)).padStart(3,'0')}`}const {data,error}=await sb.rpc('next_case_number');if(error)throw error;return data}
async function openForm(c=null){editing=c;$('modalTitle').textContent=c?'Edit Case':'Add Case';$('caseForm').reset();const m={caseNumber:'case_number',patientName:'patient_name',age:'age',sex:'sex',crUhid:'cr_uhid',wardUnit:'ward_unit',admissionDate:'admission_date',surgeryDate:'surgery_date',dischargeDate:'discharge_date',caseType:'case_type',myRole:'my_role',approach:'approach',preopDiagnosis:'preop_diagnosis',postopDiagnosis:'postop_diagnosis',procedureName:'procedure_name',procedureCategory:'procedure_category',primarySurgeon:'primary_surgeon',consultant:'consultant_supervisor',anaesthesia:'anaesthesia',assistants:'assistant_surgeons',findings:'operative_findings',operativeSteps:'operative_steps',complications:'complications',complexity:'case_complexity',supervision:'supervision',outcome:'outcome',incisionTime:'incision_time',closureTime:'closure_time',bloodLoss:'estimated_blood_loss',drainPlaced:'drain_placed',drainType:'drain_type',specimen:'specimen',hpeNumber:'hpe_number',hpeDiagnosis:'hpe_diagnosis',hpeStatus:'hpe_status',hpeSentDate:'hpe_sent_date',hpeReceivedDate:'hpe_received_date',followupDate:'followup_date',followupOutcome:'followup_outcome',remarks:'remarks'};fields.forEach(f=>{if(c)setv(f,c[m[f]]??'')});;$('caseId').value=c?.id||'';$('caseNumber').value=c?.case_number||'Generating…';$('caseNumberDisplay').textContent=c?.case_number||'Generating…';$('caseIdStatus').textContent=c?'Saved case':'Preparing ID';if(!c){const today=new Date().toISOString().slice(0,10);setv('surgeryDate',today);setv('caseType','Elective');setv('myRole','Primary Surgeon');setv('approach','Open');setv('complexity','Routine');setv('supervision','Independent');setv('outcome','Stable');try{const n=await nextCaseNumber();setv('caseNumber',n);$('caseNumberDisplay').textContent=n;$('caseIdStatus').textContent=navigator.onLine?'Cloud sequence':'Local provisional'}catch(e){const y=new Date().getFullYear();const nums=visibleCases().map(c=>c.case_number).filter(x=>x&&x.startsWith(y+'-')).map(x=>parseInt(x.slice(5),10)).filter(Number.isFinite);const n=`${y}-${String(Math.max(0,...nums)+1).padStart(3,'0')}`;setv('caseNumber',n);$('caseNumberDisplay').textContent=n;$('caseIdStatus').textContent='Local provisional'}}$('attachmentPreview').innerHTML='';$('caseModal').classList.remove('hidden');formMsg('');const draft=await idbGet(DRAFT,currentUser?.id||'');if(!c&&draft&&draft.data){if(confirm('Resume unfinished case?')){fields.forEach(f=>setv(f,draft.data[f]));$('caseNumber').value=draft.data.caseNumber||$('caseNumber').value;$('caseNumberDisplay').textContent=$('caseNumber').value}}}
function collect(){const row={id:editing?.id||uid(),user_id:currentUser.id,case_number:val('caseNumber'),patient_name:val('patientName')||null,age:val('age')?Number(val('age')):null,sex:val('sex')||null,cr_uhid:val('crUhid')||null,ward_unit:val('wardUnit')||null,admission_date:val('admissionDate')||null,surgery_date:val('surgeryDate')||null,discharge_date:val('dischargeDate')||null,case_type:val('caseType'),my_role:val('myRole'),approach:val('approach'),preop_diagnosis:val('preopDiagnosis')||null,postop_diagnosis:val('postopDiagnosis')||null,procedure_name:val('procedureName'),procedure_category:val('procedureCategory')||'Other',primary_surgeon:val('primarySurgeon')||null,assistant_surgeons:val('assistants')||null,consultant_supervisor:val('consultant')||null,anaesthesia:val('anaesthesia')||null,operative_findings:val('findings')||null,operative_steps:val('operativeSteps')||null,complications:val('complications')||null,conversion_reexploration:null,case_status:'Completed',incision_time:val('incisionTime')||null,closure_time:val('closureTime')||null,operative_duration_minutes:durationMinutes(),estimated_blood_loss:val('bloodLoss')?Number(val('bloodLoss')):null,drain_placed:val('drainPlaced'),drain_type:val('drainType')||null,specimen:val('specimen')||null,hpe_number:val('hpeNumber')||null,hpe_diagnosis:val('hpeDiagnosis')||null,hpe_status:val('hpeStatus'),hpe_sent_date:val('hpeSentDate')||null,hpe_received_date:val('hpeReceivedDate')||null,followup_date:val('followupDate')||null,followup_outcome:val('followupOutcome')||null,remarks:val('remarks')||null,is_deleted:false,deleted_at:null,updated_at:isoNow(),created_at:editing?.created_at||isoNow(),sync_status:'pending',sync_error:null};return row}
function durationMinutes(){const a=val('incisionTime'),b=val('closureTime');if(!a||!b)return null;let x=a.split(':').map(Number),y=b.split(':').map(Number),m=y[0]*60+y[1]-(x[0]*60+x[1]);if(m<0)m+=1440;return m}
function validate(row){if(!row.surgery_date||!row.procedure_name){formMsg('Surgery date and Procedure are required.');return false}if(row.admission_date&&row.surgery_date<row.admission_date){formMsg('Surgery date cannot be before admission date.');return false}if(row.discharge_date&&row.surgery_date>row.discharge_date){formMsg('Discharge date cannot be before surgery date.');return false}if(row.hpe_received_date&&row.hpe_sent_date&&row.hpe_received_date<row.hpe_sent_date){formMsg('HPE received date cannot be before sent date.');return false}if(row.incison_time&&row.closure_time){}return true}
async function similar(row){if(!row.cr_uhid&&!row.patient_name)return[];const p=visibleCases().filter(c=>c.id!==row.id&&c.surgery_date===row.surgery_date&&c.procedure_name?.toLowerCase()===row.procedure_name?.toLowerCase());return p.filter(c=>row.cr_uhid&&c.cr_uhid?c.cr_uhid===row.cr_uhid:row.patient_name&&c.patient_name?.toLowerCase()===row.patient_name?.toLowerCase())}
async function saveCase(e){e.preventDefault();const row=collect();if(!validate(row))return;const dup=await similar(row);if(dup.length&&!confirm(`Similar case already exists (${dup[0].case_number||'case'}). Save anyway?`))return;await idbPut(STORE,row);await queueFiles(row.id);await idbDelete(DRAFT,currentUser.id);cases=[...visibleCases().filter(c=>c.id!==row.id),row];renderAll();$('caseModal').classList.add('hidden');formMsg('');if(navigator.onLine)syncNow();else setSync('pending');}
async function saveDraft(){if(!currentUser||!$('caseModal')||$('caseModal').classList.contains('hidden'))return;const data={};fields.forEach(f=>data[f]=val(f));await idbPut(DRAFT,{id:currentUser.id,data,updated_at:isoNow()})}
async function syncNow(){if(!sb||!currentUser||syncing)return;syncing=true;setSync('syncing');try{const local=await idbGetAll(STORE);for(const c of local.filter(x=>x.user_id===currentUser.id&&x.sync_status!=='synced')){let row={...c};delete row.sync_status;delete row.sync_error;const {data,error}=await sb.from('cases').upsert(row,{onConflict:'id'}).select().single();if(error){c.sync_status='failed';c.sync_error=error.message;await idbPut(STORE,c);continue}c={...data,sync_status:'synced',sync_error:null};await idbPut(STORE,c)}const {data,error}=await sb.from('cases').select('*').eq('user_id',currentUser.id);if(error)throw error;for(const cloud of data||[]){const localCase=await idbGet(STORE,cloud.id);if(!localCase||new Date(cloud.updated_at||0)>=new Date(localCase.updated_at||0))await idbPut(STORE,{...cloud,sync_status:'synced',sync_error:null})}cases=(await idbGetAll(STORE)).filter(x=>x.user_id===currentUser.id);setSync(stats().pendingSync?'pending':'synced');renderAll();await syncFiles()}catch(e){console.error('sync failed',e);setSync('failed')}finally{syncing=false}}
async function syncFiles(){if(!sb||!currentUser||!navigator.onLine)return;const files=await idbGetAll(FILES);for(const f of files.filter(x=>x.user_id===currentUser.id&&x.sync_status!=='synced')){const up=await sb.storage.from('case-files').upload(f.path,f.blob,{upsert:true,contentType:f.mime});if(up.error){f.sync_status='failed';f.sync_error=up.error.message;await idbPut(FILES,f);continue}const {error}=await sb.from('case_attachments').upsert({id:f.id,user_id:f.user_id,case_id:f.case_id,file_name:f.name,file_path:f.path,category:f.category,mime_type:f.mime,file_size:f.blob.size},{onConflict:'id'});if(!error){f.sync_status='synced';f.sync_error=null;await idbPut(FILES,f)}else{f.sync_status='failed';f.sync_error=error.message;await idbPut(FILES,f)}}}
async function queueFiles(caseId){const fs=[...($('attachments').files||[])];for(const f of fs){let blob=f;if(f.type.startsWith('image/'))blob=await compressImage(f);const id=uid(),path=`${currentUser.id}/${caseId}/${id}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;await idbPut(FILES,{id,user_id:currentUser.id,case_id:caseId,name:f.name,mime:f.type,category:'Other',blob,path,sync_status:'pending',created_at:isoNow()})}if(navigator.onLine)syncFiles()}
function compressImage(file){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{const max=2200,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);c.toBlob(b=>resolve(b||file),'image/jpeg',.82)};img.onerror=()=>reject(new Error('Image decode failed'));img.src=URL.createObjectURL(file)})}
async function view(id){
  const c=cases.find(x=>x.id===id)||await idbGet(STORE,id); if(!c)return;
  let cloudAtts=[];
  if(sb&&navigator.onLine){const q=await sb.from('case_attachments').select('*').eq('case_id',id).eq('user_id',currentUser.id).order('created_at');cloudAtts=q.data||[];}
  const localFiles=(await idbGetAll(FILES)).filter(f=>f.user_id===currentUser.id&&f.case_id===id);
  const byPath=new Map(localFiles.map(f=>[f.path,f]));
  const merged=[...cloudAtts];
  for(const f of localFiles){if(!merged.some(a=>a.file_path===f.path))merged.push({id:f.id,file_name:f.name,file_path:f.path,category:f.category,mime_type:f.mime,sync_status:f.sync_status});}
  $('detailTitle').textContent=`${c.case_number||''} — ${c.procedure_name||''}`;
  const attachmentHtml=merged.length?`<div class="detail-section"><h3>Photos / Reports (${merged.length})</h3><div class="attachment-grid">${merged.map((a,i)=>{
    const isImg=(a.mime_type||'').startsWith('image/');
    const local=byPath.get(a.file_path);
    return `<button type="button" class="attachment-tile" data-path="${esc(a.file_path)}" data-id="${esc(a.id||'')}" data-local="${local?'1':'0'}"><div class="attachment-thumb">${isImg?'🖼️':'📄'}</div><div class="attachment-name">${esc(a.file_name)}</div><small>${local&&local.sync_status!=='synced'?'⚠ Pending upload':a.category||''}</small></button>`;
  }).join('')}</div></div>`:'';
  $('detailBody').innerHTML=`<div class="detail-grid">${[['Case ID',c.case_number],['Surgery date',c.surgery_date],['Type',c.case_type],['Role',c.my_role],['Approach',c.approach],['Pre-op diagnosis',c.preop_diagnosis],['Post-op diagnosis',c.postop_diagnosis],['Procedure',c.procedure_name],['Category',c.procedure_category],['Primary surgeon',c.primary_surgeon],['Assistant(s)',c.assistant_surgeons],['Consultant',c.consultant_supervisor],['Anaesthesia',c.anaesthesia],['Findings',c.operative_findings],['Operative steps',c.operative_steps],['Complications',c.complications],['Outcome',c.outcome],['Blood loss',c.estimated_blood_loss?c.estimated_blood_loss+' mL':null],['Drains',c.drain_placed==='Yes'?c.drain_type:'None'],['Specimen',c.specimen],['HPE',c.hpe_diagnosis],['HPE status',c.hpe_status],['Remarks',c.remarks]].map(([a,b])=>`<div class="detail-item"><b>${a}</b><div>${esc(b||'—')}</div></div>`).join('')}</div><div class="detail-actions"><button id="editDetail" class="primary" type="button">Edit</button><button id="duplicateDetail" class="secondary" type="button">Duplicate</button><button id="otNoteBtn" class="secondary" type="button">Generate OT Note</button><button id="deleteDetail" class="secondary" type="button">Move to Trash</button></div>${attachmentHtml}`;
  $('detailModal').classList.remove('hidden');
  $('editDetail').onclick=()=>{$('detailModal').classList.add('hidden');openForm(c)};
  $('duplicateDetail').onclick=()=>{$('detailModal').classList.add('hidden');const copy={...c,id:null,case_number:null,created_at:null};openForm(copy)};
  $('deleteDetail').onclick=async()=>{if(!confirm('Move this case to Trash?'))return;c.is_deleted=true;c.deleted_at=isoNow();c.updated_at=isoNow();c.sync_status='pending';await idbPut(STORE,c);$('detailModal').classList.add('hidden');renderAll();syncNow()};
  $('otNoteBtn').onclick=()=>showOTNote(c);
  document.querySelectorAll('.attachment-tile').forEach(b=>b.onclick=async()=>{
    const local=byPath.get(b.dataset.path);
    if(local){const url=URL.createObjectURL(local.blob);window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),60000);return;}
    if(!sb||!navigator.onLine){alert('File is not available offline yet.');return;}
    const {data,error}=await sb.storage.from('case-files').createSignedUrl(b.dataset.path,600);
    if(error){alert('Could not open file: '+error.message);return;}
    window.open(data.signedUrl,'_blank','noopener');
  });
}

function showOTNote(c){const note=[['PREOPERATIVE DIAGNOSIS',c.preop_diagnosis],['POSTOPERATIVE DIAGNOSIS',c.postop_diagnosis],['PROCEDURE',c.procedure_name],['SURGEON',c.primary_surgeon],['ASSISTANTS',c.assistant_surgeons],['CONSULTANT / SUPERVISOR',c.consultant_supervisor],['ANAESTHESIA',c.anaesthesia],['OPERATIVE FINDINGS',c.operative_findings],['PROCEDURE DETAILS',c.operative_steps],['SPECIMEN',c.specimen],['DRAINS',c.drain_placed==='Yes'?c.drain_type:'None'],['ESTIMATED BLOOD LOSS',c.estimated_blood_loss?`${c.estimated_blood_loss} mL`:null],['COMPLICATIONS',c.complications],['PATIENT CONDITION AT END OF PROCEDURE',c.outcome]].filter(x=>x[1]).map(x=>`${x[0]}\n${x[1]}`).join('\n\n');navigator.clipboard?.writeText(note);alert('OT note generated and copied. Only entered information was used.\n\n'+note)}
function exportJSON(){const data={exported_at:isoNow(),cases:visibleCases(),attachments:[]};download('surgical-logbook-backup.json',JSON.stringify(data,null,2),'application/json')}
function exportCSV(){const arr=visibleCases(),cols=['case_number','surgery_date','patient_name','cr_uhid','case_type','my_role','procedure_name','procedure_category','approach','preop_diagnosis','postop_diagnosis','primary_surgeon','assistant_surgeons','consultant_supervisor','anaesthesia','operative_findings','complications','outcome','estimated_blood_loss','drain_placed','drain_type','specimen','hpe_number','hpe_diagnosis','hpe_status','hpe_sent_date','hpe_received_date','followup_date','followup_outcome','remarks','created_at','updated_at'];const csv=[cols.join(','),...arr.map(r=>cols.map(k=>`"${String(r[k]??'').replace(/"/g,'""')}"`).join(','))].join('\n');download('surgical-logbook.csv',csv,'text/csv;charset=utf-8')}
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function printPDF(){const arr=visibleCases();const w=window.open('','_blank');if(!w)return;w.document.write(`<html><head><title>Surgical Logbook</title><style>body{font:12px Arial;padding:20px}h1{font-size:20px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #aaa;padding:5px;text-align:left}</style></head><body><h1>Surgical Logbook</h1><p>Total cases: ${arr.length}</p><table><tr><th>Case ID</th><th>Date</th><th>Procedure</th><th>Role</th><th>Type</th><th>Diagnosis</th></tr>${arr.map(c=>`<tr><td>${esc(c.case_number)}</td><td>${esc(c.surgery_date)}</td><td>${esc(c.procedure_name)}</td><td>${esc(c.my_role)}</td><td>${esc(c.case_type)}</td><td>${esc(c.preop_diagnosis||c.postop_diagnosis)}</td></tr>`).join('')}</table><script>window.print()<\/script></body></html>`);w.document.close()}
async function importFile(f){const text=await f.text();if(f.name.toLowerCase().endsWith('.json')){const j=JSON.parse(text);const arr=j.cases||[];for(const c of arr){c.id=c.id||uid();c.user_id=currentUser.id;c.sync_status='pending';await idbPut(STORE,c)} }else{const lines=text.split(/\r?\n/).filter(Boolean),headers=lines.shift().split(',').map(x=>x.replace(/^"|"$/g,''));for(const line of lines){const vals=line.match(/("(?:[^"]|"")*"|[^,]*)/g)?.filter((_,i,a)=>i<a.length-1)||[];const c={id:uid(),user_id:currentUser.id,sync_status:'pending',created_at:isoNow(),updated_at:isoNow()};headers.forEach((h,i)=>c[h]=(vals[i]||'').replace(/^"|"$/g,'').replace(/""/g,'"'));await idbPut(STORE,c)}}cases=(await idbGetAll(STORE)).filter(c=>c.user_id===currentUser.id);renderAll();if(navigator.onLine)syncNow()}
async function loadLocal(){cases=(await idbGetAll(STORE)).filter(c=>c.user_id===currentUser.id);renderAll();setSync(stats().pendingSync?'pending':navigator.onLine?'syncing':'offline')}
async function auth(){if(!sb){notify('Supabase configuration missing.');return}const hash=location.hash,search=location.search,isRecovery=/type=recovery/i.test(hash+search);sb.auth.onAuthStateChange((event,s)=>{currentUser=s?.user||null;if(event==='PASSWORD_RECOVERY'||isRecovery){if(currentUser)$('resetModal').classList.remove('hidden');return}if(currentUser){showMain();loadLocal();syncNow();setupRealtime()}else showAuth()});const {data:{session}}=await sb.auth.getSession();if(session){currentUser=session.user;showMain();await loadLocal();if(navigator.onLine)syncNow();setupRealtime()}else showAuth()}
function setupRealtime(){if(realtime||!sb||!currentUser)return;realtime=sb.channel('cases-live-'+currentUser.id).on('postgres_changes',{event:'*',schema:'public',table:'cases',filter:`user_id=eq.${currentUser.id}`},async payload=>{const c=payload.new||payload.old;if(c?.id){if(payload.eventType==='DELETE')await idbDelete(STORE,c.id);else{const local=await idbGet(STORE,c.id);if(!local||new Date(c.updated_at||0)>=new Date(local.updated_at||0))await idbPut(STORE,{...c,sync_status:'synced'})}cases=(await idbGetAll(STORE)).filter(x=>x.user_id===currentUser.id);renderAll()}}).subscribe()}
function switchAuth(mode){const phone=mode==='phone';$('emailAuth').classList.toggle('hidden',phone);$('phoneAuth').classList.toggle('hidden',!phone);$('emailTab').classList.toggle('active',!phone);$('phoneTab').classList.toggle('active',phone)}
$('loginBtn').onclick=async()=>{const {error}=await sb.auth.signInWithPassword({email:val('email'),password:val('password')});notify(error?.message||'')};$('signupBtn').onclick=async()=>{const {error}=await sb.auth.signUp({email:val('email'),password:val('password')});notify(error?.message||'Check your email.')};$('forgotBtn').onclick=async()=>{if(!val('email'))return notify('Enter your email first.');const {error}=await sb.auth.resetPasswordForEmail(val('email'),{redirectTo:'https://drperfect97-art.github.io/Surgical-logbook/'});notify(error?.message||'Recovery email sent.')};$('emailTab').onclick=()=>switchAuth('email');$('phoneTab').onclick=()=>switchAuth('phone');$('sendOtpBtn').onclick=async()=>{const {error}=await sb.auth.signInWithOtp({phone:val('loginPhone'),options:{shouldCreateUser:false}});notify(error?.message||'OTP sent.');$('loginOtp').classList.remove('hidden');$('verifyOtpBtn').classList.remove('hidden')};$('verifyOtpBtn').onclick=async()=>{const {error}=await sb.auth.verifyOtp({phone:val('loginPhone'),token:val('loginOtp'),type:'sms'});notify(error?.message||'')};
$('resetBtn').onclick=async()=>{const p=val('newPassword'),c=val('confirmPassword');if(p.length<8||p!==c)return $('resetMsg').textContent='Use 8+ characters and matching passwords.';const {error}=await sb.auth.updateUser({password:p});$('resetMsg').textContent=error?.message||'Password updated.'};$('closeReset').onclick=()=>$('resetModal').classList.add('hidden');$('logoutBtn').onclick=()=>sb.auth.signOut();$('syncBtn').onclick=syncNow;
$('addBtn').onclick=()=>openForm();$('quickAddBtn').onclick=()=>openForm();$('closeModal').onclick=()=>$('caseModal').classList.add('hidden');$('closeDetail').onclick=()=>$('detailModal').classList.add('hidden');$('detailModal').addEventListener('click',e=>{if(e.target===$('detailModal'))$('detailModal').classList.add('hidden')});$('cancelBtn').onclick=()=>$('caseModal').classList.add('hidden');$('caseForm').onsubmit=saveCase;$('incisionTime').oninput=calcDuration;$('closureTime').oninput=calcDuration;$('caseForm').oninput=()=>{clearTimeout(dirtyDraftTimer);dirtyDraftTimer=setTimeout(saveDraft,500)};$('caseList').onclick=e=>{const c=e.target.closest('.case-card');if(c)view(c.dataset.id)};$('recentList').onclick=e=>{const c=e.target.closest('.case-card');if(c)view(c.dataset.id)};$('search').oninput=renderCases;['roleFilter','typeFilter','approachFilter','yearFilter','categoryFilter','hpeFilter'].forEach(id=>$(id).onchange=renderCases);$('filterBtn').onclick=()=>$('filterPanel').classList.toggle('hidden');$('clearFilters').onclick=()=>{['roleFilter','typeFilter','approachFilter','yearFilter','categoryFilter','hpeFilter'].forEach(id=>setv(id,''));renderCases()};document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{const n=b.dataset.nav;n==='add'?openForm():showPage(n)});$('statYear').onchange=renderAnalytics;$('backupNowBtn').onclick=()=>{exportJSON();$('lastBackup').textContent=new Date().toLocaleString()};$('exportJson').onclick=exportJSON;$('exportCsv').onclick=exportCSV;$('exportPdf').onclick=printPDF;$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=e=>e.target.files[0]&&importFile(e.target.files[0]);$('settingsBtn').onclick=()=>$('settingsModal').classList.remove('hidden');$('closeSettings').onclick=()=>$('settingsModal').classList.add('hidden');$('settingsSync').onclick=syncNow;$('settingsLogout').onclick=()=>sb.auth.signOut();$('saveProfile').onclick=async()=>{const p={user_id:currentUser.id,doctor_name:val('doctorName'),hospital:val('hospital'),department:val('department'),unit:val('unit'),updated_at:isoNow()};await sb.from('user_profiles').upsert(p,{onConflict:'user_id'});alert('Profile saved')};window.addEventListener('online',()=>syncNow());window.addEventListener('offline',()=>setSync('offline'));window.addEventListener('beforeunload',saveDraft);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});auth();
