const cfg=window.SUPABASE_CONFIG||{};
const configured=cfg.url&&cfg.publishableKey&&!cfg.url.includes('PASTE_')&&!cfg.publishableKey.includes('PASTE_');
const sb=configured?window.supabase.createClient(cfg.url,cfg.publishableKey):null;
const $=id=>document.getElementById(id); let currentUser=null,cases=[],editing=null,phoneChange=null;
const fields=['caseNumber','patientName','age','sex','crUhid','admissionDate','surgeryDate','dischargeDate','wardUnit','caseType','myRole','preopDiagnosis','postopDiagnosis','procedureName','procedureCategory','approach','consultant','primarySurgeon','assistants','anaesthesia','findings','complications','complexity','supervision','outcome','bloodLoss','drains','specimen','hpeNumber','hpeDiagnosis','hpeSentDate','remarks'];
function val(id){return $(id).value.trim()} function setv(id,v){$(id).value=v??''}
function notify(msg){$('authMsg').textContent=msg}
function setSync(online){$('syncBadge').textContent=online?'Synced':'Offline';$('syncBadge').classList.toggle('online',online)}
function renderStats(){const n=cases.length; const p=cases.filter(x=>x.my_role==='Primary').length; const a=cases.filter(x=>x.my_role?.includes('Assistant')).length; const e=cases.filter(x=>x.case_type==='Emergency').length;$('stats').innerHTML=[['Total',n],['Primary',p],['Assistant',a],['Emergency',e]].map(x=>`<div class="stat"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')}
function renderFilters(){const months=[...new Set(cases.map(x=>x.surgery_date).filter(Boolean).map(x=>x.slice(0,7)))].sort().reverse();$('monthFilter').innerHTML='<option value="">All dates</option>'+months.map(m=>`<option value="${m}">${m}</option>`).join('')}
function filtered(){const q=$('search').value.toLowerCase(),r=$('roleFilter').value,t=$('typeFilter').value,m=$('monthFilter').value;return cases.filter(x=>{const blob=JSON.stringify(x).toLowerCase();return(!q||blob.includes(q))&&(!r||x.my_role===r)&&(!t||x.case_type===t)&&(!m||x.surgery_date?.startsWith(m))}).sort((a,b)=>(b.surgery_date||'').localeCompare(a.surgery_date||''))}
function render(){renderStats();renderFilters();const arr=filtered();$('caseList').innerHTML=arr.length?arr.map(x=>`<article class="case-card" data-id="${x.id}"><div><h3>${x.case_number||'Draft'} — ${esc(x.procedure_name)}</h3><div class="case-meta">${x.surgery_date||'No surgery date'} · ${esc(x.my_role||'')} · ${esc(x.case_type||'')}<br>${esc(x.preop_diagnosis||'')}<br><span class="pill">${esc(x.approach||'')}</span><span class="pill">${esc(x.consultant||'')}</span></div></div><button class="secondary openBtn">View</button></article>`).join(''):'<div class="empty">No cases found.<br>Add your first case.</div>'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function load(){if(!sb||!currentUser)return;const {data,error}=await sb.from('cases').select('*').eq('user_id',currentUser.id).eq('is_deleted',false).order('surgery_date',{ascending:false});if(error){notify(error.message);return}cases=data||[];setSync(navigator.onLine);render()}
function openForm(c=null){editing=c;$('modalTitle').textContent=c?'Edit Case':'Add Case';$('caseForm').reset();$('caseId').value=c?.id||'';fields.forEach(id=>{if(c&&id!=='caseId')setv(id,c[id])});$('modal').classList.remove('hidden');$('formMsg').textContent=''}
async function saveCase(e){e.preventDefault();$('formMsg').textContent='Saving…';if(!currentUser){$('formMsg').textContent='Please sign in.';return}let id=editing?.id;let caseNumber=editing?.case_number;if(!caseNumber){const {data,error}=await sb.rpc('next_case_number');if(error){$('formMsg').textContent=error.message;return}caseNumber=data}const row={user_id:currentUser.id,case_number:caseNumber};const map={caseNumber:'case_number',patientName:'patient_name',age:'age',sex:'sex',crUhid:'cr_uhid',admissionDate:'admission_date',surgeryDate:'surgery_date',dischargeDate:'discharge_date',wardUnit:'ward_unit',caseType:'case_type',myRole:'my_role',preopDiagnosis:'preop_diagnosis',postopDiagnosis:'postop_diagnosis',procedureName:'procedure_name',procedureCategory:'procedure_category',approach:'approach',consultant:'consultant_supervisor',primarySurgeon:'primary_surgeon',assistants:'assistant_surgeons',anaesthesia:'anaesthesia',findings:'operative_findings',complications:'complications',complexity:'case_complexity',supervision:'supervision',outcome:'outcome',bloodLoss:'blood_loss_ml',drains:'drains',specimen:'specimen',hpeNumber:'hpe_number',hpeDiagnosis:'hpe_diagnosis',hpeSentDate:'hpe_sent_date',remarks:'additional_remarks'};Object.entries(map).forEach(([a,b])=>{let v=$(a).value.trim();if(a==='age'||a==='bloodLoss')v=v?Number(v):null;row[b]=v||null});let res=editing?await sb.from('cases').update(row).eq('id',id).eq('user_id',currentUser.id).select().single():await sb.from('cases').insert(row).select().single();if(res.error){$('formMsg').textContent=res.error.message;return}const saved=res.data;const files=[...($('attachments').files||[])];for(const f of files){const path=`${currentUser.id}/${saved.id}/${Date.now()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await sb.storage.from('case-files').upload(path,f,{upsert:false});if(up.error){$('formMsg').textContent='Case saved, attachment failed: '+up.error.message;continue}await sb.from('case_attachments').insert({user_id:currentUser.id,case_id:saved.id,file_name:f.name,file_path:path,attachment_type:f.type==='application/pdf'?'HPE/Report':'Other',mime_type:f.type,file_size:f.size})}$('modal').classList.add('hidden');await load()}
async function view(id){const c=cases.find(x=>x.id===id);if(!c)return;const {data:atts}=await sb.from('case_attachments').select('*').eq('case_id',id).eq('user_id',currentUser.id).order('created_at');$('detailTitle').textContent=`${c.case_number||''} — ${c.procedure_name||''}`;$('detailBody').innerHTML=`<div class="detail-grid">${[['Surgery date',c.surgery_date],['Role',c.my_role],['Type',c.case_type],['Approach',c.approach],['Pre-op',c.preop_diagnosis],['Post-op',c.postop_diagnosis],['Consultant',c.consultant_supervisor],['Findings',c.operative_findings],['Complications',c.complications],['Outcome',c.outcome],['HPE',c.hpe_diagnosis],['Remarks',c.additional_remarks]].map(([a,b])=>`<div class="detail-item"><b>${a}</b><div>${esc(b||'—')}</div></div>`).join('')}</div><div class="detail-actions"><button id="editDetail" class="primary">Edit</button><button id="deleteDetail" class="secondary">Move to Trash</button></div>${atts?.length?`<h3>Attachments</h3><ul>${atts.map(a=>`<li>${esc(a.file_name)}</li>`).join('')}</ul>`:''}`;$('detailModal').classList.remove('hidden');$('editDetail').onclick=()=>{$('detailModal').classList.add('hidden');openForm(c)};$('deleteDetail').onclick=async()=>{if(confirm('Move this case to Trash?')){await sb.from('cases').update({is_deleted:true,deleted_at:new Date().toISOString()}).eq('id',id).eq('user_id',currentUser.id);$('detailModal').classList.add('hidden');load()}}}
function showResetModal(){$('resetModal').classList.remove('hidden');$('newPassword').value='';$('confirmPassword').value='';$('resetMsg').textContent='Choose a new password.'}
async function requestRecovery(){const email=val('email');if(!email){notify('Enter your email first.');return}notify('Sending password recovery email…');const redirectTo=window.location.origin+window.location.pathname;const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo});notify(error?.message||'Recovery email sent. Check Gmail and open the newest email.')}
async function finishRecovery(){const p=val('newPassword'),c=val('confirmPassword');if(p.length<8){$('resetMsg').textContent='Password should be at least 8 characters.';return}if(p!==c){$('resetMsg').textContent='Passwords do not match.';return}$('resetMsg').textContent='Updating password…';const {error}=await sb.auth.updateUser({password:p});if(error){$('resetMsg').textContent=error.message;return}$('resetMsg').textContent='Password updated successfully.';setTimeout(()=>{$('resetModal').classList.add('hidden');showMain()},500)}
async function auth(){if(!sb){notify('Open config.js and add your Supabase Project URL + Publishable key.');return}sb.auth.onAuthStateChange((event,s)=>{if(event==='PASSWORD_RECOVERY'){currentUser=s?.user||null;showResetModal();return}currentUser=s?.user||null;if(currentUser){showMain();load()}else{showAuth()}});const {data:{session}}=await sb.auth.getSession();if(session){currentUser=session.user;showMain();await load()}const hash=window.location.hash||'';if(hash.includes('error_code=otp_expired')||window.location.search.includes('error_code=otp_expired')){notify('This recovery link has expired or was already used. Request a NEW recovery email and open the newest link.')}}
function showMain(){$('authView').classList.add('hidden');$('mainView').classList.remove('hidden');$('logoutBtn').classList.remove('hidden');$('settingsBtn').classList.remove('hidden');notify('');loadAccountPhone()}
function showAuth(){$('authView').classList.remove('hidden');$('mainView').classList.add('hidden');$('logoutBtn').classList.add('hidden');$('settingsBtn').classList.add('hidden')}
function switchAuth(mode){const phone=mode==='phone';$('emailAuth').classList.toggle('hidden',phone);$('phoneAuth').classList.toggle('hidden',!phone);$('emailTab').classList.toggle('active',!phone);$('phoneTab').classList.toggle('active',phone);notify('')}
async function loadAccountPhone(){if(!currentUser)return;const {data}=await sb.auth.getUser();const phone=data?.user?.phone||'';$('accountPhone').value=phone}
$('emailTab').onclick=()=>switchAuth('email');$('phoneTab').onclick=()=>switchAuth('phone');
$('loginBtn').onclick=async()=>{if(!sb)return auth();const {error}=await sb.auth.signInWithPassword({email:val('email'),password:val('password')});notify(error?.message||'')};
$('signupBtn').onclick=async()=>{if(!sb)return auth();const {error}=await sb.auth.signUp({email:val('email'),password:val('password')});notify(error?.message||'Check your email if confirmation is enabled.')};
$('sendOtpBtn').onclick=async()=>{const phone=val('loginPhone');if(!phone){notify('Enter phone number with country code, e.g. +919876543210');return}notify('Sending OTP…');const {error}=await sb.auth.signInWithOtp({phone,options:{shouldCreateUser:false}});if(error){notify(error.message);return}$('loginOtp').classList.remove('hidden');$('verifyOtpBtn').classList.remove('hidden');notify('OTP sent. Enter the 6-digit code.')};
$('verifyOtpBtn').onclick=async()=>{const phone=val('loginPhone'),token=val('loginOtp');if(!token){notify('Enter the OTP.');return}const {error}=await sb.auth.verifyOtp({phone,token,type:'sms'});notify(error?.message||'')};
$('forgotBtn').onclick=requestRecovery; $('resetBtn').onclick=finishRecovery; $('closeReset').onclick=()=>$('resetModal').classList.add('hidden');
$('logoutBtn').onclick=()=>sb?.auth.signOut();
$('settingsBtn').onclick=()=>{$('settingsModal').classList.remove('hidden');loadAccountPhone()};$('closeSettings').onclick=()=>$('settingsModal').classList.add('hidden');
$('sendPhoneChange').onclick=async()=>{const phone=val('accountPhone');if(!phone){$('phoneMsg').textContent='Enter a phone number with country code.';return} $('phoneMsg').textContent='Sending OTP…';const {error}=await sb.auth.updateUser({phone});if(error){$('phoneMsg').textContent=error.message;return}phoneChange=phone;$('phoneOtpWrap').classList.remove('hidden');$('verifyPhoneChange').classList.remove('hidden');$('phoneMsg').textContent='OTP sent. Enter the 6-digit code.'};
$('verifyPhoneChange').onclick=async()=>{const token=val('phoneChangeOtp');if(!phoneChange||!token){$('phoneMsg').textContent='Enter the OTP.';return}const {error}=await sb.auth.verifyOtp({phone:phoneChange,token,type:'phone_change'});$('phoneMsg').textContent=error?.message||'Phone verified and linked.';if(!error){currentUser=(await sb.auth.getUser()).data.user;phoneChange=null}};
$('addBtn').onclick=()=>openForm();$('closeModal').onclick=()=>$('modal').classList.add('hidden');$('cancelBtn').onclick=()=>$('modal').classList.add('hidden');$('closeDetail').onclick=()=>$('detailModal').classList.add('hidden');$('caseForm').onsubmit=saveCase;['search','roleFilter','typeFilter','monthFilter'].forEach(id=>$(id).addEventListener('input',render));$('caseList').onclick=e=>{const card=e.target.closest('.case-card');if(card)view(card.dataset.id)};window.addEventListener('online',()=>setSync(true));window.addEventListener('offline',()=>setSync(false));
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});auth();
